- name: copy mongo repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue & get the categories count
  ansible.builtin.command: mongosh 172.31.28.20 --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host 172.31.28.20 </app/db/master-data.js
  when: catalogue_output.stdout | int < 0